name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} crpi-r8cio2xv4rcpn2ug.cn-hangzhou.personal.cr.aliyuncs.com

          cd xxl-job-admin
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag crpi-r8cio2xv4rcpn2ug.cn-hangzhou.personal.cr.aliyuncs.com/fisherbyxiang/xxl-job-admin:2.4.2
          # 推送镜像到镜像仓库
          docker push crpi-r8cio2xv4rcpn2ug.cn-hangzhou.personal.cr.aliyuncs.com/fisherbyxiang/xxl-job-admin:2.4.2
